package com.flyingogo.flyingterminal.module;

import java.io.Serializable;

/**
 * 作者：dfy on 22/7/2017 16:43
 * <p>   支付宝支付请求;
 * 邮箱：dengfuyao@163.com
 */

public class AliPayRechargeBean implements Serializable {
    /**
     * tradeStatus : SUCCESS
     * resultType : {"state":1001,"message":"0.48"}
     * outTradeNo : 2017072811053801368
     * rechargeAmount : 0.01
     * cardNo : 5970100007
     * imgurl : iVBORw0KGgoAAAANSUhEUgAAAQAAAAEACAIAAADTED8xAAAE4UlEQVR42u3dMXLEMAwEQf3/0+cvOBAWS6ontk8nk80AxSo/P+nDPf4EAkACQAJAAkACQAJAAkACQAJAAkACQAJAAkACQAJAAkACQAJAAkACQAJAAkACQAJAAkACQAJAugrAs9rcN/zP5ySf1f8WyTUFAAAAAAAAAAAAAAAAAAAAAAAAGgAMTrJeelYS0tw2nXv3E9cUAAAAAAAAAAAAAAAAAAAAAAAAaABw6yDyO4Pj3TUFAAAAAAAAAAAAAAAAAAAAAAAAAGgbVu6ySY5BAQAAAAAAAAAAAAAAAAAAAAAAAADaACQ37h2/BQAAAAAAAAAAAAAAAAAAAAAAAACw+AKji9dGPfle/WsKAAAAAAAAAAAAAAAAAAAAAAAAdAJItovkOz+zu6YAAAAAAAAAAIBNCQAANiUAANi4ADQAaKt/xJncBIsbrm5jAAAAAAAAAAAAAAAAAAAAAAAAAPMb7riR2W/yH+klx83fWS8AAAAAAAAAAAAAAAAAAAAAAACgYQy6O+bbZZMcyyYZH0cCAAAAAAAAAAAAAAAAAAAAAAAAKBmMJkeuc0R3n548IOb+YgAAAAAAAAAAAAAAAAAAAAAAAMDXACRHeMlv2D+I3L3SBwAAAAAAAAAAAAAAAAAAAAAAAHQCSF6KalvO5Hi3f0i9+14AAAAAAAAAAAAAAAAAAAAAAABAwxh0cfg1yib5pm0HTXLcDAAAAAAAAAAAAAAAAAAAAAAAAJwLYG481zYYTR4Qu5fzkp8DAAAAAAAAAAAAAAAAAAAAAAAA5AEkN+7uJpjD1n99sO1ZAAAAAAAAAAAAAAAAAAAAAAAAQAOA/jFo20gx+aZz65U8egAAAAAAAAAAAAAAAAAAAAAAAIA8gLnN1LaV267r7TZHCwAAAAAAAAAAAAAAAAAAAAAAALhpDJpchl20u9fRkoda+XcGAAAAAAAAAAAAAAAAAAAAAAAAAiPOuctVuyT6kSSvtc0dagAAAAAAAAAAAAAAAAAAAAAAAMApAJIbbm4Yl9xMbYyTvwUAAAAAAAAAAAAAAAAAAAAAAACcAmD3SlZy6yT5JcepycuLAAAAAAAAAAAAAAAAAAAAAAAAwE1j0N2F2R1Wzl012316kjoAAAAAAAAAAAAAAAAAAAAAAABwLoA5JMkh4x1j0N1tGnsWAAAAAAAAAAAAAAAAAAAAAAAAUDIGbbtu1TaETQ40594UAAAAAAAAAAAAAAAAAAAAAAAAOBdAW3dsyuTR03ZAAAAAAAAAAAAAAAAAAAAAAAAAAKeMQduGnrufkxwTz7Fpww8AAAAAAAAAAAAAAAAAAAAAAAA0AEiOOOd+JgngLRLJ9do91AAAAAAAAAAAAAAAAAAAAAAAAIBOAG/9IZIbrn9TJmkl8QMAAAAAAAAAAAAAAAAAAAAAAAAA9I8d58Z8bVfx5r4zAAAAAAAAAAAAAAAAAAAAAAAAAMCJw8p+xlcOPQEAAAAAAAAAAAAAAAAAAAAAAIAVALvP2l28ObS7o8ndwwgAAAAAAAAAAAAAAAAAAAAAAABoANA2jEs+vR/AHInkJwMAAAAAAAAAAAAAAAAAAAAAAAB5ANIRASAAJAAkACQAJAAkACQAJAAkACQAJAAkACQAJAAkACQAJAAkACQAJAAkACQAJAAkACQAJAAkAKSd/gAcvyuo3JQcuAAAAABJRU5ErkJggg==
     */

    public String         tradeStatus;
    /**
     * state : 1001
     * message : 0.48
     */

    public ResultTypeBean resultType;
    public String outTradeNo;  //订单编号;
    public String rechargeAmount;
    public String cardNo;
    public String imgurl;

    public  class ResultTypeBean implements Serializable{
        public int    state;
        public String message;
    }


    /**
     * tradeStatus : SUCCESS
     * resultType : {"state":1001,"message":"预订单生成"}
     * outTradeNo : 2017072810122752736
     * cardNo : 5970100007
     * filePath : iVBORw0KGgoAAAANSUhEUgAAAQAAAAEACAIAAADTED8xAAAE70lEQVR42u3aQZKjQBAEQf3/07N/WOvKym48zjNCApxDGr8/6cP9nAIBIAEgASABIAEgASABIAEgASABIAEgASABIAEgASABIAEgASABIAEgASABIAEgASABIAEgASA9BeC32v99w+Sv2P0+bWfj1DUFAAAAAAAAAAAAAAAAAAAAAAAAGgAMLlmHjnXq1tm9TefO4Y3XFAAAAAAAAAAAAAAAAAAAAAAAAGgAsDvhnTrpSX6vDscAAAAAAAAAAAAAAAAAAAAAAAAAAP0vcs39rrnpNvkQAQAAAAAAAAAAAAAAAAAAAAAAAADon0HnbtPd/2p70AAAAAAAAAAAAAAAAAAAAAAAAABvA9jFduNtMffbb7ymAAAAAAAAAAAAAAAAAAAAAAAAQCeAZEkkX/6b3WsKAAAAAAAAAAC4KQEAwE0JAABuXAAaALS1C2n3VbzdY7XfGAAAAAAAAAAAAAAAAAAAAAAAAMDpU5yc1ea+89zI+AbsqokTAAAAAAAAAAAAAAAAAAAAAAAAKJlB227u/ikw+epbEsDimQcAAAAAAAAAAAAAAAAAAAAAAAACl2qOze5cOPed33jQ7N4/AAAAAAAAAAAAAAAAAAAAAAAAQOeotzvhtc2pc7+ibb4EAAAAAAAAAAAAAAAAAAAAAAAAvgYgeWHaLmdycu0fsgEAAAAAAAAAAAAAAAAAAAAAAIBOAHMn/RSbtpExeTPdONQCAAAAAAAAAAAAAAAAAAAAAAAAXwOw+1/Jz5kbNJOfXD6MAgAAAAAAAAAAAAAAAAAAAAAAAAESc3PY3LGSQ23ba39t1wIAAAAAAAAAAAAAAAAAAAAAAAC4dwZNDoj9U+Dc38xNpVU3NwAAAAAAAAAAAAAAAAAAAAAAALACIHlqdvndOJ7OPTIWX3QDAAAAAAAAAAAAAAAAAAAAAAAAAgDeYJOcStsGxN1X3x58GxQAAAAAAAAAAAAAAAAAAAAAAB4FkJzV/p4oOTsmb8ryqwwAAAAAAAAAAAAAAAAAAAAAAAAERrS2U3zq6MmZL/kq3u7YDQAAAAAAAAAAAAAAAAAAAAAAALw9g86dmuRQO0creSv3X1MAAAAAAAAAAAAAAAAAAAAAAACgcwbdvSnnvs/c58yNsHOzbPkLjgAAAAAAAAAAAAAAAAAAAAAAAMAKgP52+SXRzv32KhIAAAAAAAAAAAAAAAAAAAAAAABAAMDchNd2qZJH3x2gd18EBAAAAAAAAAAAAAAAAAAAAAAAAPIAbpwv+wfNuUdP8mW4uaMDAAAAAAAAAAAAAAAAAAAAAAAADTNo/9DWNvP1f5/klAwAAAAAAAAAAAAAAAAAAAAAAADcAiA5ce4Of8n/anv5bPexAgAAAAAAAAAAAAAAAAAAAAAAAHQCSL6gduPM10/rutETAAAAAAAAAAAAAAAAAAAAAAAA+CCAtuFv7uhtV2dx9AQAAAAAAAAAAAAAAAAAAAAAAAAAOHg5k2dsd+KsGjQBAAAAAAAAAAAAAAAAAAAAAACAWgBtx0qSmEM7B6ntHAIAAAAAAAAAAAAAAAAAAAAAAACdAHbHuN0X1NoA7J6f3cclAAAAAAAAAAAAAAAAAAAAAAAAIH0wAASABIAEgASABIAEgASABIAEgASABIAEgASABIAEgASABIAEgASABIAEgASABIAEgASABIAEgLTTP6VpsT7QdpAyAAAAAElFTkSuQmCC
     */

   /* public String         tradeStatus;
    *//**
     * state : 1001
     * message : 预订单生成
     *//*

    public ResultTypeBean resultType;
    public String outTradeNo;
    public String cardNo;
    public String filePath;

    public  class ResultTypeBean implements Serializable {
        public int    state;
        public String message;
    }*/

}
